"""Browse and inspect individual weekly RAG reports."""
from __future__ import annotations

import streamlit as st

from api_client import ApiError, cached_weekly_reports, get, render_api_status_sidebar

st.set_page_config(page_title="Weekly Reports", page_icon="\U0001F4C4", layout="wide")
render_api_status_sidebar()

RAG_BADGE = {"Green": "🟢", "Amber": "🟠", "Red": "🔴"}

st.title("Weekly Reports")
st.caption("Every weekly RAG report currently on disk, one per project per run.")

try:
    reports = cached_weekly_reports()
except ApiError as exc:
    st.error(str(exc))
    st.stop()

if not reports:
    st.info("No weekly reports yet — head to **Run Agent** to generate the first one.")
    st.stop()

project_options = sorted({r["project_slug"] for r in reports})
selected_slug = st.selectbox(
    "Project",
    project_options,
    format_func=lambda slug: next(
        (r["project_name"] for r in reports if r["project_slug"] == slug), slug
    ),
)

weeks_for_project = sorted(
    [r for r in reports if r["project_slug"] == selected_slug],
    key=lambda r: r["week_ending"],
    reverse=True,
)
week_options = [r["week_ending"] for r in weeks_for_project]
selected_week = st.selectbox("Week ending", week_options)

try:
    report = get(f"/weekly/reports/{selected_slug}/{selected_week}")
except ApiError as exc:
    st.error(str(exc))
    st.stop()

badge = RAG_BADGE.get(report["final_rag_status"], "⚪")
st.header(f"{badge} {report['project_name']} — {report['final_rag_status']}")

col1, col2, col3 = st.columns(3)
col1.metric("Composite score", report["composite_score"])
col2.metric("Data completeness", f"{report['data_completeness']:.0%}")
col3.metric("Generated by", report.get("generated_by", "—"))

if report.get("source_vs_computed_disagreement"):
    d = report["source_vs_computed_disagreement"]
    st.warning(
        f"**Source vs. computed disagreement:** source file said "
        f"**{d['source_value']}**, agent computed **{d['computed_value']}**. {d['note']}"
    )

if report.get("model_vs_deterministic_disagreement"):
    st.info(report["model_vs_deterministic_disagreement"])

st.subheader("Plain-English reasoning")
st.write(report.get("plain_english_reasoning", "—"))

col_a, col_b = st.columns(2)
with col_a:
    st.subheader("Top drivers")
    for d in report.get("top_drivers") or []:
        st.markdown(f"- {d}")
with col_b:
    st.subheader("Recommended actions")
    for a in report.get("recommended_actions") or []:
        st.markdown(f"- {a}")

if report.get("overrides_triggered"):
    st.subheader("Overrides triggered")
    for o in report["overrides_triggered"]:
        st.markdown(f"- {o}")

st.subheader("Signal breakdown")
signals = report.get("signal_breakdown", {})
if signals:
    for name, info in signals.items():
        with st.expander(f"{name.replace('_', ' ').title()} — score {info.get('score')}"):
            st.write(info.get("detail", ""))
            extra = {k: v for k, v in info.items() if k not in ("score", "detail", "examples")}
            if extra:
                st.json(extra)
            if info.get("examples"):
                st.caption("Examples:")
                for ex in info["examples"]:
                    st.markdown(f"> {ex}")

st.divider()
try:
    docx_bytes = get(f"/weekly/reports/{selected_slug}/{selected_week}/docx")
    st.download_button(
        "⬇️ Download .docx report",
        data=docx_bytes,
        file_name=f"{selected_slug}_{selected_week}.docx",
        mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    )
except ApiError:
    st.caption("No .docx available for this report.")
